Add optional section with additional data to html report
behave-contrib/behave-html-pretty-formatter pull request #12
Opened 2022-12-13 16:20 UTC by lu-maca

![here](https://user-images.githubusercontent.com/65252677/207385730-10cdabc7-87c4-43b4-81ac-b5312e6143bc.png)
As shown in the picture above, I added the possibility to put some additional information to the summary of the report. In particular, these additional info are added for each "behave.additional-info.something" in the [behave.userdata] section in behave.ini. In the example above:

[behave.userdata]
behave.additional-info.tester=lumaca
behave.additional-info.board=multiboard

2022-12-20 10:12 UTC, fpokryvk requested changes
Thank you for your work on this. There is small thing to change in the code, see inline comment. Please squash the first and the last commit (so unused function is not added at all). Also, after changing CSS or JS, please run `tox -e minify` to compile minified versions and commit them as well.

2022-12-20 10:12 UTC, fpokryvk commented on behave_html_pretty_formatter/html_pretty.py
> +            if formatter.additional_info:
Toggle summary will not work for this, if it is not inside `feature-summary-container`. Either add `feature-aditional-info-container` to javascript. Or better, put this block inside `feature-summary-container` (one more indent + additional change to CSS may be needed).

2022-12-22 16:18 UTC, lu-maca commented
Hi @fpokryvk, 
thanks for your comments. I've updated all the stuff, but I'm not sure how to squash all the commits of an already opened pull request. How can I do that without messing up all the work?

2022-12-22 19:58 UTC, bittner commented
> I'm not sure how to squash all the commits of an already opened pull request. How can I do that without messing up all the work?

Locally, you would do an interactive rebase (to squash i.e. combine your commits into a single commit) and then force-push the result to this PR.

```console
git rebase -i HEAD~5
```
```console
git push -f
```

Here is some background reading:

- https://www.git-tower.com/learn/git/faq/git-squash/
- https://duckduckgo.com/?t=ffab&q=git+squash&atb=v155-1&iax=videos&ia=videos

2022-12-22 20:27 UTC, lu-maca commented
Thanks @bittner for the references!

Now it should be ok

2022-12-23 13:47 UTC, fpokryvk requested changes
And final change, in `setup.py` change version to "1.3" and we are good to go. I have run this locally without style="display..." line and seems fine.

2022-12-23 13:47 UTC, fpokryvk commented on behave_html_pretty_formatter/html_pretty.py
> +                        style=f"display: {summary_display}"
This line is wrong. It makes additional info never show, if there is "show_summary = false" in config. Please drop this line.

2022-12-23 16:41 UTC, fpokryvk commented on behave_html_pretty_formatter/html_pretty.py
> +                        style=f"display: {summary_display}"
And also short mention in `CHANGES` what is new in 1.3. Thanks a lot.

2022-12-24 08:27 UTC, fpokryvk commented
Check are failing, code should be black formatted, so please delete mentioned `style=f"display..."` line and format by `black`. I can do CHANGES and version increase when I will create the package.

2022-12-24 11:32 UTC, fpokryvk commented
Also, please not this issue #9, so there is a chance of repositioning additional data. Plan so far is to make it 3-column flex `div` (scenario counts, expand buttons, time and additional data), that will be responsive for small width too.

2022-12-24 18:49 UTC, lu-maca commented
Hi @fpokryvk,

I've fixed that line and reformatted according to black. I leave all the changes in setup.py to you :)

2022-12-24 19:08 UTC, fpokryvk approved these changes
Looks good, sorry for initial delay. All checks passed. Merging.

2022-12-24 19:09 UTC, merged

2022-12-24 19:26 UTC, fpokryvk commented
And 1.3 is live in pip! Thanks for nice feature!